/** Esquema de columnas: una sola fila con absolutamente todos los campos. */

export const BANDS = {
  medico: { label: "Médico", className: "band-medico" },
  sesion: { label: "Sesión", className: "band-sesion" },
  interrogatorio: { label: "Interrogatorio", className: "band-interro" },
  ubicacion: { label: "Ubicación sesión", className: "band-ubic" },
  ambiente: { label: "Ambiente", className: "band-amb" },
  examen: { label: "Exploración", className: "band-exam" },
  metro: { label: "Parpadeómetro", className: "band-metro" },
  interf: { label: "Interferometría", className: "band-interf" },
  raw: { label: "JSON completo", className: "band-raw" },
};

function col(key, label, band) {
  return { key, label, band };
}

/** Columnas del bloque médico (registro). */
export const MEDICO_COLS = [
  col("registeredAt", "Alta", "medico"),
  col("displayName", "Nombre", "medico"),
  col("fullName", "Nombre completo", "medico"),
  col("nickname", "Apodo", "medico"),
  col("email", "Email", "medico"),
  col("phone", "Teléfono", "medico"),
  col("age", "Edad médico", "medico"),
  col("ophthalmologyProfile", "Perfil oftalmológico", "medico"),
  col("specialtyLabel", "Especialidad", "medico"),
  col("specialtySlug", "Especialidad slug", "medico"),
  col("specialtyOther", "Especialidad otra", "medico"),
  col("medicoLocCity", "Ciudad médico", "medico"),
  col("medicoLocSource", "Loc. médico origen", "medico"),
  col("medicoLocLabel", "Loc. médico etiqueta", "medico"),
  col("medicoLocLat", "Loc. médico lat", "medico"),
  col("medicoLocLng", "Loc. médico lng", "medico"),
  col("medicoLocAccuracy", "Loc. médico precisión", "medico"),
  col("locationDeclined", "Médico sin localización", "medico"),
  col("active", "Activo", "medico"),
  col("role", "Rol", "medico"),
  col("counts.parpadeo", "Nº envíos Parpadeo", "medico"),
  col("counts.parpadeoCompleted", "Nº Parpadeo completos", "medico"),
  col("counts.interferometria", "Nº Interferometría", "medico"),
  col("counts.total", "Nº total envíos", "medico"),
  col("medicoLocationJson", "Médico location JSON", "raw"),
];

/** Prefijos de protocolo en flat de médicos. */
export function protocolCols(prefix, bandDone = "sesion") {
  const p = (key, label, band) => col(`${prefix}${key}`, label, band);
  return [
    p("Done", "Hecho", bandDone),
    p("Status", "Estado", bandDone),
    p("CreatedAt", "Creada", bandDone),
    p("CompletedAt", "Completada", bandDone),
    p("SessionId", "ID sesión", bandDone),
    p("Protocol", "Protocolo", bandDone),
    p("SujetoEdad", "Edad sujeto", "interrogatorio"),
    p("SujetoSexo", "Sexo", "interrogatorio"),
    p("OjoSecoDx", "Dx ojo seco", "interrogatorio"),
    p("TratamientoNoLubricante", "Trat. no lubricante", "interrogatorio"),
    p("UsaLubricante", "Usa lubricante", "interrogatorio"),
    p("Osdi6Hecho", "OSDI-6 hecho", "interrogatorio"),
    p("Osdi6Q1", "OSDI Q1", "interrogatorio"),
    p("Osdi6Q2", "OSDI Q2", "interrogatorio"),
    p("Osdi6Q3", "OSDI Q3", "interrogatorio"),
    p("Osdi6Q4", "OSDI Q4", "interrogatorio"),
    p("Osdi6Q5", "OSDI Q5", "interrogatorio"),
    p("Osdi6Q6", "OSDI Q6", "interrogatorio"),
    p("Osdi6Total", "OSDI total", "interrogatorio"),
    p("Osdi6PosibleOjoSeco", "OSDI posible ojo seco", "interrogatorio"),
    p("Osdi6Discomfort", "OSDI malestar", "interrogatorio"),
    p("Osdi6VisualFunction", "OSDI función visual", "interrogatorio"),
    p("Osdi6Environmental", "OSDI ambiental", "interrogatorio"),
    p("SesionLocSource", "Sesión loc. origen", "ubicacion"),
    p("SesionLocCity", "Sesión localidad", "ubicacion"),
    p("SesionLocLabel", "Sesión loc. etiqueta", "ubicacion"),
    p("SesionLocLat", "Sesión lat", "ubicacion"),
    p("SesionLocLng", "Sesión lng", "ubicacion"),
    p("SesionLocAccuracy", "Sesión precisión", "ubicacion"),
    p("SesionLocSameLocality", "Misma localidad", "ubicacion"),
    p("SesionLocCapturedAt", "Sesión loc. capturada", "ubicacion"),
    p("EnvSource", "Ambiente origen", "ambiente"),
    p("EnvCapturedAt", "Ambiente capturado", "ambiente"),
    p("EnvLat", "Ambiente lat", "ambiente"),
    p("EnvLng", "Ambiente lng", "ambiente"),
    p("EnvTempC", "Temp °C", "ambiente"),
    p("EnvHumidityPct", "Humedad %", "ambiente"),
    p("EnvPressureMsl", "Presión MSL", "ambiente"),
    p("EnvSurfacePressure", "Presión superficie", "ambiente"),
    p("EnvUvIndex", "UV", "ambiente"),
    p("EnvWindKmh", "Viento km/h", "ambiente"),
    p("EnvPm25", "PM2.5", "ambiente"),
    p("EnvPm10", "PM10", "ambiente"),
    p("EnvDust", "Polvo", "ambiente"),
    p("EnvOzone", "Ozono", "ambiente"),
    p("EnvNo2", "NO2", "ambiente"),
    p("EnvAqiEu", "AQI EU", "ambiente"),
    p("EnvAqiUs", "AQI US", "ambiente"),
    p("TbutOd", "TBUT OD", "examen"),
    p("TbutOs", "TBUT OS", "examen"),
    p("SchirmerOd", "Schirmer OD", "examen"),
    p("SchirmerOs", "Schirmer OS", "examen"),
    p("TincionOdConjIzq", "Tinción OD conj. izq", "examen"),
    p("TincionOdCornea", "Tinción OD córnea", "examen"),
    p("TincionOdConjDer", "Tinción OD conj. der", "examen"),
    p("TincionOdParches", "Tinción OD parches", "examen"),
    p("TincionOdPupilar", "Tinción OD pupilar", "examen"),
    p("TincionOdFilamentos", "Tinción OD filamentos", "examen"),
    p("TincionOsConjIzq", "Tinción OS conj. izq", "examen"),
    p("TincionOsCornea", "Tinción OS córnea", "examen"),
    p("TincionOsConjDer", "Tinción OS conj. der", "examen"),
    p("TincionOsParches", "Tinción OS parches", "examen"),
    p("TincionOsPupilar", "Tinción OS pupilar", "examen"),
    p("TincionOsFilamentos", "Tinción OS filamentos", "examen"),
    p("MeibomioFuncionOd", "Meibomio función OD", "examen"),
    p("MeibomioFuncionOs", "Meibomio función OS", "examen"),
    p("MeibomioExpOd", "Meibomio expres. OD", "examen"),
    p("MeibomioExpOs", "Meibomio expres. OS", "examen"),
    p("Hallazgo_thickenedMargin_od", "Margen engrosado OD", "examen"),
    p("Hallazgo_thickenedMargin_os", "Margen engrosado OS", "examen"),
    p("Hallazgo_irregularMargin_od", "Margen irregular OD", "examen"),
    p("Hallazgo_irregularMargin_os", "Margen irregular OS", "examen"),
    p("Hallazgo_telangiectasia_od", "Telangiectasia OD", "examen"),
    p("Hallazgo_telangiectasia_os", "Telangiectasia OS", "examen"),
    p("Hallazgo_distichiasis_od", "Distiquiasis OD", "examen"),
    p("Hallazgo_distichiasis_os", "Distiquiasis OS", "examen"),
    p("Hallazgo_madarosis_od", "Madarosis OD", "examen"),
    p("Hallazgo_madarosis_os", "Madarosis OS", "examen"),
    p("Hallazgo_malposition_od", "Malposición OD", "examen"),
    p("Hallazgo_malposition_os", "Malposición OS", "examen"),
    p("Hallazgo_mucocutaneousJunction_od", "Unión mucocutánea OD", "examen"),
    p("Hallazgo_mucocutaneousJunction_os", "Unión mucocutánea OS", "examen"),
    p("Orificio_pouting_od", "Orificio pouting OD", "examen"),
    p("Orificio_pouting_os", "Orificio pouting OS", "examen"),
    p("Orificio_capping_od", "Orificio capping OD", "examen"),
    p("Orificio_capping_os", "Orificio capping OS", "examen"),
    p("Orificio_lossOfDefinition_od", "Pérdida definición OD", "examen"),
    p("Orificio_lossOfDefinition_os", "Pérdida definición OS", "examen"),
    p("Orificio_vascularInvasion_od", "Invasión vascular OD", "examen"),
    p("Orificio_vascularInvasion_os", "Invasión vascular OS", "examen"),
    p("Orificio_orificeNarrowing_od", "Estrechamiento OD", "examen"),
    p("Orificio_orificeNarrowing_os", "Estrechamiento OS", "examen"),
    p("Orificio_posteriorToMarx_od", "Posterior a Marx OD", "examen"),
    p("Orificio_posteriorToMarx_os", "Posterior a Marx OS", "examen"),
    p("Plus_irreversibleDamage", "Plus daño irreversible", "examen"),
    p("Plus_schirmerZero", "Plus Schirmer 0", "examen"),
    p("Plus_lagophthalmos", "Plus lagoftalmos", "examen"),
    p("Plus_symblepharon", "Plus simbléfaron", "examen"),
    p("Plus_cornealAnesthesia", "Plus anestesia corneal", "examen"),
    p("Plus_keratinization", "Plus queratinización", "examen"),
    p("Parpadeos", "Parpadeos", "metro"),
    p("Incompletos", "Incompletos", "metro"),
    p("Bpm", "BPM", "metro"),
    p("MediaIntervalo", "Media intervalo s", "metro"),
    p("MedianaIntervalo", "Mediana intervalo s", "metro"),
    p("ModaIntervalo", "Moda intervalo s", "metro"),
    p("ArritmiaCv", "Arritmia CV %", "metro"),
    p("DuracionMs", "Duración ms", "metro"),
    p("Umbral", "Umbral apertura", "metro"),
    p("MeterFinishedAt", "Metro finalizado", "metro"),
    p("AnswersJson", "Answers JSON", "raw"),
    p("SesionLocJson", "Sesión loc JSON", "raw"),
    p("EnvJson", "Ambiente JSON", "raw"),
    p("ExamJson", "Exam JSON", "raw"),
    p("MeterJson", "Meter JSON", "raw"),
  ];
}

export const MEDICOS_COLUMNS = [
  ...MEDICO_COLS,
  ...protocolCols("parpadeo", "sesion").map((c) => ({
    ...c,
    label: `Parpadeo · ${c.label}`,
  })),
  ...protocolCols("interf", "interf").map((c) => ({
    ...c,
    label: `Interferometría · ${c.label}`,
    band: c.band === "sesion" ? "interf" : c.band,
  })),
];

/** Intervenciones: médico + todos los campos de esa sesión (sin prefijo). */
export const INTERVENCION_COLUMNS = [
  col("createdAt", "Fecha sesión", "sesion"),
  col("completedAt", "Completada", "sesion"),
  col("status", "Estado", "sesion"),
  col("protocol", "Protocolo", "sesion"),
  col("sessionId", "ID sesión", "sesion"),
  col("researcherRegisteredAt", "Alta médico", "medico"),
  col("researcherName", "Nombre médico", "medico"),
  col("researcherEmail", "Email", "medico"),
  col("researcherPhone", "Teléfono", "medico"),
  col("researcherAge", "Edad médico", "medico"),
  col("researcherNickname", "Apodo", "medico"),
  col("researcherProfile", "Perfil oftalmológico", "medico"),
  col("researcherSpecialty", "Especialidad", "medico"),
  col("researcherSpecialtySlug", "Especialidad slug", "medico"),
  col("researcherSpecialtyOther", "Especialidad otra", "medico"),
  col("medicoLocCity", "Ciudad médico", "medico"),
  col("medicoLocSource", "Loc. médico origen", "medico"),
  col("medicoLocLabel", "Loc. médico etiqueta", "medico"),
  col("medicoLocLat", "Loc. médico lat", "medico"),
  col("medicoLocLng", "Loc. médico lng", "medico"),
  col("researcherLocationDeclined", "Médico sin localización", "medico"),
  col("researcherActive", "Activo", "medico"),
  col("researcherRole", "Rol", "medico"),
  col("sujetoEdad", "Edad sujeto", "interrogatorio"),
  col("sujetoSexo", "Sexo", "interrogatorio"),
  col("ojoSecoDx", "Dx ojo seco", "interrogatorio"),
  col("tratamientoNoLubricante", "Trat. no lubricante", "interrogatorio"),
  col("usaLubricante", "Usa lubricante", "interrogatorio"),
  col("osdi6Hecho", "OSDI-6 hecho", "interrogatorio"),
  col("osdi6Q1", "OSDI Q1", "interrogatorio"),
  col("osdi6Q2", "OSDI Q2", "interrogatorio"),
  col("osdi6Q3", "OSDI Q3", "interrogatorio"),
  col("osdi6Q4", "OSDI Q4", "interrogatorio"),
  col("osdi6Q5", "OSDI Q5", "interrogatorio"),
  col("osdi6Q6", "OSDI Q6", "interrogatorio"),
  col("osdi6Total", "OSDI total", "interrogatorio"),
  col("osdi6PosibleOjoSeco", "OSDI posible ojo seco", "interrogatorio"),
  col("osdi6Discomfort", "OSDI malestar", "interrogatorio"),
  col("osdi6VisualFunction", "OSDI función visual", "interrogatorio"),
  col("osdi6Environmental", "OSDI ambiental", "interrogatorio"),
  col("sesionLocSource", "Sesión loc. origen", "ubicacion"),
  col("sesionLocCity", "Sesión localidad", "ubicacion"),
  col("sesionLocLabel", "Sesión loc. etiqueta", "ubicacion"),
  col("sesionLocLat", "Sesión lat", "ubicacion"),
  col("sesionLocLng", "Sesión lng", "ubicacion"),
  col("sesionLocAccuracy", "Sesión precisión", "ubicacion"),
  col("sesionLocSameLocality", "Misma localidad", "ubicacion"),
  col("sesionLocCapturedAt", "Sesión loc. capturada", "ubicacion"),
  col("envSource", "Ambiente origen", "ambiente"),
  col("envCapturedAt", "Ambiente capturado", "ambiente"),
  col("envLat", "Ambiente lat", "ambiente"),
  col("envLng", "Ambiente lng", "ambiente"),
  col("envTempC", "Temp °C", "ambiente"),
  col("envHumidityPct", "Humedad %", "ambiente"),
  col("envPressureMsl", "Presión MSL", "ambiente"),
  col("envSurfacePressure", "Presión superficie", "ambiente"),
  col("envUvIndex", "UV", "ambiente"),
  col("envWindKmh", "Viento km/h", "ambiente"),
  col("envPm25", "PM2.5", "ambiente"),
  col("envPm10", "PM10", "ambiente"),
  col("envDust", "Polvo", "ambiente"),
  col("envOzone", "Ozono", "ambiente"),
  col("envNo2", "NO2", "ambiente"),
  col("envAqiEu", "AQI EU", "ambiente"),
  col("envAqiUs", "AQI US", "ambiente"),
  col("tbutOd", "TBUT OD", "examen"),
  col("tbutOs", "TBUT OS", "examen"),
  col("schirmerOd", "Schirmer OD", "examen"),
  col("schirmerOs", "Schirmer OS", "examen"),
  col("tincionOdConjIzq", "Tinción OD conj. izq", "examen"),
  col("tincionOdCornea", "Tinción OD córnea", "examen"),
  col("tincionOdConjDer", "Tinción OD conj. der", "examen"),
  col("tincionOdParches", "Tinción OD parches", "examen"),
  col("tincionOdPupilar", "Tinción OD pupilar", "examen"),
  col("tincionOdFilamentos", "Tinción OD filamentos", "examen"),
  col("tincionOsConjIzq", "Tinción OS conj. izq", "examen"),
  col("tincionOsCornea", "Tinción OS córnea", "examen"),
  col("tincionOsConjDer", "Tinción OS conj. der", "examen"),
  col("tincionOsParches", "Tinción OS parches", "examen"),
  col("tincionOsPupilar", "Tinción OS pupilar", "examen"),
  col("tincionOsFilamentos", "Tinción OS filamentos", "examen"),
  col("meibomioFuncionOd", "Meibomio función OD", "examen"),
  col("meibomioFuncionOs", "Meibomio función OS", "examen"),
  col("meibomioExpOd", "Meibomio expres. OD", "examen"),
  col("meibomioExpOs", "Meibomio expres. OS", "examen"),
  col("hallazgo_thickenedMargin_od", "Margen engrosado OD", "examen"),
  col("hallazgo_thickenedMargin_os", "Margen engrosado OS", "examen"),
  col("hallazgo_irregularMargin_od", "Margen irregular OD", "examen"),
  col("hallazgo_irregularMargin_os", "Margen irregular OS", "examen"),
  col("hallazgo_telangiectasia_od", "Telangiectasia OD", "examen"),
  col("hallazgo_telangiectasia_os", "Telangiectasia OS", "examen"),
  col("hallazgo_distichiasis_od", "Distiquiasis OD", "examen"),
  col("hallazgo_distichiasis_os", "Distiquiasis OS", "examen"),
  col("hallazgo_madarosis_od", "Madarosis OD", "examen"),
  col("hallazgo_madarosis_os", "Madarosis OS", "examen"),
  col("hallazgo_malposition_od", "Malposición OD", "examen"),
  col("hallazgo_malposition_os", "Malposición OS", "examen"),
  col("hallazgo_mucocutaneousJunction_od", "Unión mucocutánea OD", "examen"),
  col("hallazgo_mucocutaneousJunction_os", "Unión mucocutánea OS", "examen"),
  col("orificio_pouting_od", "Orificio pouting OD", "examen"),
  col("orificio_pouting_os", "Orificio pouting OS", "examen"),
  col("orificio_capping_od", "Orificio capping OD", "examen"),
  col("orificio_capping_os", "Orificio capping OS", "examen"),
  col("orificio_lossOfDefinition_od", "Pérdida definición OD", "examen"),
  col("orificio_lossOfDefinition_os", "Pérdida definición OS", "examen"),
  col("orificio_vascularInvasion_od", "Invasión vascular OD", "examen"),
  col("orificio_vascularInvasion_os", "Invasión vascular OS", "examen"),
  col("orificio_orificeNarrowing_od", "Estrechamiento OD", "examen"),
  col("orificio_orificeNarrowing_os", "Estrechamiento OS", "examen"),
  col("orificio_posteriorToMarx_od", "Posterior a Marx OD", "examen"),
  col("orificio_posteriorToMarx_os", "Posterior a Marx OS", "examen"),
  col("plus_irreversibleDamage", "Plus daño irreversible", "examen"),
  col("plus_schirmerZero", "Plus Schirmer 0", "examen"),
  col("plus_lagophthalmos", "Plus lagoftalmos", "examen"),
  col("plus_symblepharon", "Plus simbléfaron", "examen"),
  col("plus_cornealAnesthesia", "Plus anestesia corneal", "examen"),
  col("plus_keratinization", "Plus queratinización", "examen"),
  col("parpadeos", "Parpadeos", "metro"),
  col("incompletos", "Incompletos", "metro"),
  col("bpm", "BPM", "metro"),
  col("mediaIntervalo", "Media intervalo s", "metro"),
  col("medianaIntervalo", "Mediana intervalo s", "metro"),
  col("modaIntervalo", "Moda intervalo s", "metro"),
  col("arritmiaCv", "Arritmia CV %", "metro"),
  col("duracionMs", "Duración ms", "metro"),
  col("umbral", "Umbral apertura", "metro"),
  col("meterFinishedAt", "Metro finalizado", "metro"),
  col("answersJson", "Answers JSON", "raw"),
  col("sesionLocJson", "Sesión loc JSON", "raw"),
  col("envJson", "Ambiente JSON", "raw"),
  col("examJson", "Exam JSON", "raw"),
  col("meterJson", "Meter JSON", "raw"),
];
